title: Mihyun's Awesome GitHub
author: xianeml
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nice! I'm happy to know you.

# social links
github_username:  xianeml # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
